// FIX: Define and export constants for application data and translations.
import { AppInfo, Language, TranslationSet } from './types';

export const APPS_DATA: AppInfo[] = [
  {
    id: 'chatbot-assistant',
    name: 'AI Chatbot Assistant',
    description: 'Design intelligent chatbots to automate customer support and sales processes tailored to your business needs.',
    icon: '🤖',
    price: 'Unlock with Pro Plan',
    embed_url: 'https://widgetbot.io/',
    category: 'Automation',
    isUnlocked: false,
  },
  {
    id: 'content-creator',
    name: 'AI Content Creator',
    description: 'Generate high-quality marketing copy, blog posts, and social media content in seconds with our advanced AI writer.',
    icon: '✍️',
    price: '99,000 VND',
    embed_url: 'https://www.google.com/search?igu=1',
    category: 'Content',
    isUnlocked: false,
  },
  {
    id: 'image-generator',
    name: 'AI Image Generator',
    description: 'Create stunning visuals and graphics for your brand from simple text descriptions. Perfect for marketing and design.',
    icon: '🎨',
    price: '129,000 VND',
    embed_url: '', // Not used for this app type, but required by type
    category: 'Image Generation',
    isUnlocked: false,
  },
  {
    id: 'voice-assistant',
    name: 'AI Voice Assistant',
    description: 'Implement a voice-controlled assistant for your applications, providing a hands-free user experience.',
    icon: '🗣️',
    price: '149,000 VND',
    embed_url: 'https://www.google.com/search?igu=1',
    category: 'Productivity',
    isUnlocked: true, // Let's have one unlocked by default for demonstration
  },
];

type Translations = {
  [key in Language]: TranslationSet;
}

export const TRANSLATIONS: Translations = {
  en: {
    header: {
      features: 'Features',
      apps: 'AI Apps',
      pricing: 'Pricing',
      affiliate: 'Affiliate',
      about: 'About Us',
      login: 'Log In',
      signup: 'Sign Up',
    },
    hero: {
      title: 'Your AI Co-pilot for Business Growth',
      subtitle: 'INTELLIGENT, AUTOMATED, EFFICIENT',
      description: 'DMP AI Studio provides a suite of powerful AI applications designed to automate tasks, enhance creativity, and drive your business forward.',
      cta: 'Explore AI Apps',
    },
    features: {
      title: 'Why Choose DMP AI Studio?',
      items: [
        { icon: 'cubes', title: 'Diverse AI Toolkit', description: 'Access a wide array of AI-powered tools for content, design, automation, and more.' },
        { icon: 'plugs-connected', title: 'Seamless Integration', description: 'Easily connect our AI apps with your existing workflows and business systems.' },
        { icon: 'magic-wand', title: 'Intuitive & User-Friendly', description: 'Our platform features clean interfaces that require no coding knowledge to operate.' },
        { icon: 'scales', title: 'Scalable Solutions', description: 'From solo entrepreneurs to large enterprises, our solutions grow with your business.' },
        { icon: 'headset', title: 'Dedicated Support', description: 'Receive expert customer support and benefit from continuous platform updates.' },
        { icon: 'shield-check', title: 'Secure & Reliable', description: 'Trust in a secure and dependable platform built to protect your valuable data.' },
      ],
    },
    apps: {
      title: 'Explore Our AI Applications',
      description: 'Discover the right tools to supercharge your productivity and innovation.',
      searchPlaceholder: 'Search apps by name or description...',
      noAppsFound: 'No applications found matching your search.',
      categories: {
        all: 'All',
        content: 'Content',
        automation: 'Automation',
        design: 'Design',
        productivity: 'Productivity',
        imageGeneration: 'Image Generation',
      },
      sorting: {
        label: 'Sort by...',
        asc: 'Name (A-Z)',
        desc: 'Name (Z-A)',
      },
    },
    pricing: {
      title: 'Flexible Plans for Every Need',
      plans: [
        { name: 'Basic', price: '99,000', unit: 'VND/mo', cta: 'Get Started', recommended: false, features: ['Access to 2 AI Apps', '10,000 AI Credits/mo', 'Email Support'] },
        { name: 'Pro', price: '199,000', unit: 'VND/mo', cta: 'Choose Pro', recommended: true, features: ['Access to All AI Apps', '25,000 AI Credits/mo', 'Priority Support', 'API Access'] },
        { name: 'Enterprise', price: '499,000', unit: 'VND/mo', cta: 'Contact Us', recommended: false, features: ['Unlimited AI Apps', 'Custom Credit Limit', 'Dedicated Account Manager', 'On-premise Deployment'] },
      ],
    },
    affiliate: {
      title: 'Join Our Affiliate Program',
      description: 'Earn commissions by promoting DMP AI Studio. Partner with us and grow together.',
      cta: 'Open Dashboard',
    },
    developerZone: {
      title: 'Developer Zone',
      description: 'Are you an AI developer? Showcase your application on our platform and reach a wider audience. Submit your app for review.',
      cta: 'Embed App',
    },
    footer: {
      copy: '© 2024 DMP AI Studio. All rights reserved.',
      social: 'Follow us',
      backToTop: 'Back to Top',
      about: 'About Us',
    },
    chatWidget: {
      welcomeMessage: "Hello! I'm your AI Business Agent. How can I help you explore DMP AI Studio today?",
      agentName: 'DMP AI Agent',
      placeholder: 'Ask about apps, pricing...',
    },
    specializedChat: {
        agentFor: 'AI Agent for',
        welcomeMessage: 'Hello! I am the specialized AI assistant for this app. I can answer your questions or help you with your purchase. How can I assist?',
        proceedToPayment: 'Proceed to Payment',
    },
    appModal: {
      unlock: 'Unlock App',
      loading: 'Loading Application...'
    },
    submitAppModal: {
        title: 'Submit Your AI Application',
        name: 'App Name',
        description: 'App Description',
        embedUrl: 'Embed URL',
        pricingModel: 'Pricing Model',
        oneTimeFee: 'One-time Fee',
        subscription: 'Subscription',
        price: 'Price (VND)',
        submit: 'Submit for Review',
        close: 'Close',
        submitSuccess: 'Application submitted successfully! It is now live on the platform.',
    },
    paymentModal: {
      title: 'Complete Your Purchase',
      payWith: 'Pay with',
      processing: 'Processing Payment...',
      success: 'Payment Successful!',
      affiliateCode: 'Affiliate Code (Optional)',
      affiliatePlaceholder: 'Enter affiliate code',
      youSelected: 'You have selected the',
      bankTransfer: 'Bank Transfer',
      momoWallet: 'Momo Wallet',
      paypal: 'PayPal',
      creditCard: 'Credit/Debit Card',
      accountNumber: 'Account Number',
      accountHolder: 'Account Holder',
      bankName: 'Bank',
      transferContent: 'Transfer Content (Order ID)',
      scanQR: 'Scan QR code to pay',
      paymentConfirmation: 'I have completed the payment',
      copy: 'Copy',
      copied: 'Copied!',
      momoPhoneNumber: 'Momo Phone Number',
      paypalEmail: 'PayPal Email',
    },
    affiliateDashboard: {
        title: 'Affiliate Dashboard',
        yourLink: 'Your Affiliate Link',
        copy: 'Copy',
        copied: 'Copied!',
        performance: 'Performance Overview',
        clicks: 'Clicks',
        sales: 'Sales',
        commission: 'Commission',
        recentSales: 'Recent Sales',
        date: 'Date',
        product: 'Product',
        payoutSummary: 'Payout Summary',
        balance: 'Current Balance',
        requestPayout: 'Request Payout',
        close: 'Close',
    },
    aboutModal: {
        title: 'About DMP AI Studio',
        content: `DMP AI Studio is a comprehensive AI solution platform designed to empower businesses and individuals. We integrate Multi-Agent AI, automated payments, and an affiliate revenue sharing system into a modern, responsive design with a high-end UX/UI. Our mission is to make advanced AI accessible and easy to use, providing multilingual support for Vietnamese, English, and Chinese to serve a global audience.
        <br /><br />
        <b>Contact Information:</b><br />
        AI Development Team: DMP AI Dev<br />
        Address: 06 Nguyen Binh, Vi Da Ward, Hue City, Vietnam<br />
        Tel: +84 0766771509 (Vietnam)<br />
        Whatsapp: +84 0766771509<br />
        Mail: dmpdevai@gmail.com / minhphu1509@gmail.com`,
        close: 'Close',
    },
    imageGeneratorModal: {
        title: 'AI Image Generator',
        promptPlaceholder: 'e.g., A photo of a cat astronaut riding a rocket through a galaxy',
        generate: 'Generate Image',
        generating: 'Generating...',
        error: 'Failed to generate image. Please try again.',
        close: 'Close',
        saveImage: 'Save Image',
        saveImageFilenamePrompt: 'Enter a filename for your image (e.g., my-cat.png):',
        agentTitle: 'AI Art Assistant',
        welcomeMessage: 'Hello! I can help you craft the perfect prompt. What would you like to create?',
        chatPlaceholder: 'Ask for prompt ideas...',
    },
  },
  vi: {
    header: {
      features: 'Tính năng',
      apps: 'Ứng dụng AI',
      pricing: 'Bảng giá',
      affiliate: 'Tiếp thị liên kết',
      about: 'Về chúng tôi',
      login: 'Đăng nhập',
      signup: 'Đăng ký',
    },
    hero: {
      title: 'Trợ lý AI cho Doanh nghiệp của bạn',
      subtitle: 'THÔNG MINH, TỰ ĐỘNG, HIỆU QUẢ',
      description: 'DMP AI Studio cung cấp bộ ứng dụng AI mạnh mẽ được thiết kế để tự động hóa công việc, nâng cao sáng tạo và thúc đẩy doanh nghiệp của bạn.',
      cta: 'Khám phá ứng dụng',
    },
    features: {
      title: 'Tại sao chọn DMP AI Studio?',
      items: [
        { icon: 'cubes', title: 'Bộ công cụ AI đa dạng', description: 'Truy cập vào một loạt các công cụ AI cho nội dung, thiết kế, tự động hóa, v.v.' },
        { icon: 'plugs-connected', title: 'Tích hợp liền mạch', description: 'Dễ dàng kết nối các ứng dụng AI của chúng tôi với quy trình làm việc hiện có của bạn.' },
        { icon: 'magic-wand', title: 'Trực quan & Thân thiện', description: 'Nền tảng của chúng tôi có giao diện tinh gọn, không yêu cầu kiến thức lập trình.' },
        { icon: 'scales', title: 'Giải pháp Linh hoạt', description: 'Từ cá nhân đến doanh nghiệp lớn, giải pháp của chúng tôi phát triển cùng bạn.' },
        { icon: 'headset', title: 'Hỗ trợ Tận tâm', description: 'Nhận hỗ trợ chuyên nghiệp và hưởng lợi từ các bản cập nhật liên tục.' },
        { icon: 'shield-check', title: 'An toàn & Tin cậy', description: 'Tin tưởng vào một nền tảng an toàn và đáng tin cậy để bảo vệ dữ liệu của bạn.' },
      ],
    },
    apps: {
      title: 'Khám phá các ứng dụng AI của chúng tôi',
      description: 'Tìm kiếm công cụ phù hợp để tăng cường năng suất và sự đổi mới.',
      searchPlaceholder: 'Tìm kiếm ứng dụng theo tên hoặc mô tả...',
      noAppsFound: 'Không tìm thấy ứng dụng nào phù hợp với tìm kiếm của bạn.',
      categories: {
        all: 'Tất cả',
        content: 'Nội dung',
        automation: 'Tự động hóa',
        design: 'Thiết kế',
        productivity: 'Năng suất',
        imageGeneration: 'Tạo hình ảnh',
      },
      sorting: {
        label: 'Sắp xếp theo...',
        asc: 'Tên (A-Z)',
        desc: 'Tên (Z-A)',
      },
    },
    pricing: {
      title: 'Các gói linh hoạt cho mọi nhu cầu',
      plans: [
        { name: 'Cơ bản', price: '99,000', unit: 'VND/tháng', cta: 'Bắt đầu', recommended: false, features: ['Truy cập 2 ứng dụng AI', '10,000 Tín dụng AI/tháng', 'Hỗ trợ qua Email'] },
        { name: 'Chuyên nghiệp', price: '199,000', unit: 'VND/tháng', cta: 'Chọn gói Pro', recommended: true, features: ['Truy cập tất cả ứng dụng AI', '25,000 Tín dụng AI/tháng', 'Hỗ trợ Ưu tiên', 'Truy cập API'] },
        { name: 'Doanh nghiệp', price: '499,000', unit: 'VND/tháng', cta: 'Liên hệ', recommended: false, features: ['Không giới hạn ứng dụng', 'Hạn mức Tín dụng tùy chỉnh', 'Quản lý tài khoản riêng', 'Triển khai tại chỗ'] },
      ],
    },
    affiliate: {
      title: 'Tham gia Chương trình Liên kết',
      description: 'Kiếm hoa hồng bằng cách quảng bá DMP AI Studio. Hợp tác và cùng nhau phát triển.',
      cta: 'Mở Bảng điều khiển',
    },
    developerZone: {
      title: 'Khu vực nhà phát triển',
      description: 'Bạn là nhà phát triển AI? Giới thiệu ứng dụng của bạn trên nền tảng của chúng tôi và tiếp cận nhiều người dùng hơn. Gửi ứng dụng của bạn để được xem xét.',
      cta: 'Nhúng ứng dụng',
    },
    footer: {
      copy: '© 2024 DMP AI Studio. Mọi quyền được bảo lưu.',
      social: 'Theo dõi chúng tôi',
      backToTop: 'Về đầu trang',
      about: 'Về chúng tôi',
    },
    chatWidget: {
      welcomeMessage: "Xin chào! Tôi là Trợ lý Kinh doanh AI. Tôi có thể giúp bạn khám phá DMP AI Studio như thế nào?",
      agentName: 'Agent AI của DMP',
      placeholder: 'Hỏi về ứng dụng, giá cả...',
    },
    specializedChat: {
        agentFor: 'Agent AI cho',
        welcomeMessage: 'Xin chào! Tôi là trợ lý AI chuyên biệt cho ứng dụng này. Tôi có thể trả lời câu hỏi hoặc giúp bạn tiến hành mua hàng. Tôi có thể giúp gì cho bạn?',
        proceedToPayment: 'Tiến hành thanh toán',
    },
    appModal: {
      unlock: 'Mở khóa ứng dụng',
      loading: 'Đang tải ứng dụng...'
    },
    submitAppModal: {
        title: 'Gửi ứng dụng AI của bạn',
        name: 'Tên ứng dụng',
        description: 'Mô tả ứng dụng',
        embedUrl: 'URL nhúng',
        pricingModel: 'Mô hình định giá',
        oneTimeFee: 'Phí một lần',
        subscription: 'Theo dõi (tháng)',
        price: 'Giá (VND)',
        submit: 'Gửi để xem xét',
        close: 'Đóng',
        submitSuccess: 'Gửi ứng dụng thành công! Ứng dụng của bạn đã có mặt trên nền tảng.',
    },
    paymentModal: {
      title: 'Hoàn tất thanh toán',
      payWith: 'Thanh toán với',
      processing: 'Đang xử lý thanh toán...',
      success: 'Thanh toán thành công!',
      affiliateCode: 'Mã liên kết (Tùy chọn)',
      affiliatePlaceholder: 'Nhập mã liên kết',
      youSelected: 'Bạn đã chọn',
      bankTransfer: 'Chuyển khoản Ngân hàng',
      momoWallet: 'Ví Momo',
      paypal: 'PayPal',
      creditCard: 'Thẻ Tín dụng/Ghi nợ',
      accountNumber: 'Số tài khoản',
      accountHolder: 'Chủ tài khoản',
      bankName: 'Ngân hàng',
      transferContent: 'Nội dung chuyển khoản (Mã đơn hàng)',
      scanQR: 'Quét mã QR để thanh toán',
      paymentConfirmation: 'Tôi đã hoàn tất thanh toán',
      copy: 'Sao chép',
      copied: 'Đã chép!',
      momoPhoneNumber: 'Số điện thoại Momo',
      paypalEmail: 'Email PayPal',
    },
    affiliateDashboard: {
        title: 'Bảng điều khiển Affiliate',
        yourLink: 'Link Affiliate của bạn',
        copy: 'Sao chép',
        copied: 'Đã chép!',
        performance: 'Tổng quan Hiệu suất',
        clicks: 'Lượt nhấp',
        sales: 'Đơn hàng',
        commission: 'Hoa hồng',
        recentSales: 'Đơn hàng Gần đây',
        date: 'Ngày',
        product: 'Sản phẩm',
        payoutSummary: 'Tổng kết Thanh toán',
        balance: 'Số dư Hiện tại',
        requestPayout: 'Yêu cầu Thanh toán',
        close: 'Đóng',
    },
    aboutModal: {
        title: 'Về DMP AI Studio',
        content: `DMP AI Studio là một nền tảng giải pháp AI toàn diện được thiết kế để trao quyền cho các doanh nghiệp và cá nhân. Chúng tôi tích hợp AI Đa tác tử, thanh toán tự động và hệ thống chia sẻ doanh thu tiếp thị liên kết vào một thiết kế hiện đại, đáp ứng với UX/UI cao cấp. Sứ mệnh của chúng tôi là làm cho AI tiên tiến có thể truy cập và dễ sử dụng, cung cấp hỗ trợ đa ngôn ngữ cho tiếng Việt, tiếng Anh và tiếng Trung để phục vụ khán giả toàn cầu.
        <br /><br />
        <b>Thông tin liên hệ:</b><br />
        Tên nhóm phát triển trí tuệ nhân tạo: DMP AI Dev<br />
        Địa chỉ: 06 Nguyễn Bính, P Vĩ Dạ, Tp Huế, Việt Nam<br />
        Tel: +84 0766771509 ( Việt Nam)<br />
        Whatsapp: +84 0766771509<br />
        Mail: dmpdevai@gmail.com / minhphu1509@gmail.com`,
        close: 'Đóng',
    },
    imageGeneratorModal: {
        title: 'AI Tạo hình ảnh',
        promptPlaceholder: 'Ví dụ: Ảnh một chú mèo phi hành gia cưỡi tên lửa xuyên qua dải ngân hà',
        generate: 'Tạo ảnh',
        generating: 'Đang tạo...',
        error: 'Tạo ảnh thất bại. Vui lòng thử lại.',
        close: 'Đóng',
        saveImage: 'Lưu ảnh',
        saveImageFilenamePrompt: 'Nhập tên tệp cho ảnh của bạn (ví dụ: meo-cua-toi.png):',
        agentTitle: 'Trợ lý nghệ thuật AI',
        welcomeMessage: 'Xin chào! Tôi có thể giúp bạn tạo ra prompt hoàn hảo. Bạn muốn tạo ra điều gì?',
        chatPlaceholder: 'Hỏi ý tưởng về prompt...',
    },
  },
  zh: {
    header: {
      features: '特征',
      apps: 'AI 应用',
      pricing: '价钱',
      affiliate: '加盟',
      about: '关于我们',
      login: '登录',
      signup: '注册',
    },
    hero: {
      title: '您的业务增长 AI 副驾驶',
      subtitle: '智能、自动化、高效',
      description: 'DMP AI Studio 提供一套强大的 AI 应用程序，旨在自动化任务、增强创造力并推动您的业务向前发展。',
      cta: '探索 AI 应用',
    },
    features: {
      title: '为什么选择 DMP AI Studio？',
      items: [
        { icon: 'cubes', title: '多样化的 AI 工具包', description: '访问用于内容、设计、自动化等的各种 AI 驱动工具。' },
        { icon: 'plugs-connected', title: '无缝集成', description: '轻松将我们的 AI 应用与您现有的工作流程和业务系统连接。' },
        { icon: 'magic-wand', title: '直观且用户友好', description: '我们的平台具有简洁的界面，无需编码知识即可操作。' },
        { icon: 'scales', title: '可扩展的解决方案', description: '从个体企业家到大型企业，我们的解决方案与您的业务共同成长。' },
        { icon: 'headset', title: '专属支持', description: '获得专业的客户支持并受益于持续的平台更新。' },
        { icon: 'shield-check', title: '安全可靠', description: '信赖一个安全可靠的平台来保护您的宝贵数据。' },
      ],
    },
    apps: {
      title: '探索我们的 AI 应用程序',
      description: '发现合适的工具来提高您的生产力和创新能力。',
      searchPlaceholder: '按名称或描述搜索应用...',
      noAppsFound: '未找到与您的搜索匹配的应用程序。',
      categories: {
        all: '全部',
        content: '内容',
        automation: '自动化',
        design: '设计',
        productivity: '生产力',
        imageGeneration: '图像生成',
      },
      sorting: {
        label: '排序方式...',
        asc: '名称 (A-Z)',
        desc: '名称 (Z-A)',
      },
    },
    pricing: {
      title: '灵活的计划满足各种需求',
      plans: [
        { name: '基本', price: '99,000', unit: '越南盾/月', cta: '开始使用', recommended: false, features: ['访问 2 个 AI 应用', '10,000 AI 积分/月', '电子邮件支持'] },
        { name: '专业版', price: '199,000', unit: '越南盾/月', cta: '选择专业版', recommended: true, features: ['访问所有 AI 应用', '25,000 AI 积分/月', '优先支持', 'API 访问'] },
        { name: '企业版', price: '499,000', unit: '越南盾/月', cta: '联系我们', recommended: false, features: ['无限 AI 应用', '自定义信用额度', '专属客户经理', '本地部署'] },
      ],
    },
    affiliate: {
      title: '加入我们的联盟计划',
      description: '通过推广 DMP AI Studio 赚取佣金。与我们合作，共同成长。',
      cta: '打开仪表板',
    },
    developerZone: {
      title: '开发者专区',
      description: '您是 AI 开发者吗？在我们的平台上展示您的应用程序，并接触更广泛的受众。提交您的应用以供审核。',
      cta: '嵌入应用',
    },
    footer: {
      copy: '© 2024 DMP AI Studio。版权所有。',
      social: '关注我们',
      backToTop: '返回顶部',
      about: '关于我们',
    },
    chatWidget: {
      welcomeMessage: '你好！我是您的 AI 业务代理。我今天如何帮助您探索 DMP AI Studio？',
      agentName: 'DMP AI 代理',
      placeholder: '询问有关应用程序、定价...',
    },
    specializedChat: {
        agentFor: 'AI 代理为',
        welcomeMessage: '你好！我是此应用程序的专业 AI 助理。我可以回答您的问题或帮助您购买。我该如何协助您？',
        proceedToPayment: '进行付款',
    },
    appModal: {
      unlock: '解锁应用',
      loading: '正在加载应用程序...'
    },
    submitAppModal: {
        title: '提交您的 AI 应用程序',
        name: '应用名称',
        description: '应用描述',
        embedUrl: '嵌入 URL',
        pricingModel: '定价模式',
        oneTimeFee: '一次性费用',
        subscription: '订阅',
        price: '价格 (越南盾)',
        submit: '提交审核',
        close: '关闭',
        submitSuccess: '应用提交成功！它现在已在平台上线。',
    },
    paymentModal: {
      title: '完成您的购买',
      payWith: '使用...付款',
      processing: '正在处理付款...',
      success: '付款成功！',
      affiliateCode: '联盟代码（可选）',
      affiliatePlaceholder: '输入联盟代码',
      youSelected: '您选择了',
      bankTransfer: '银行转帐',
      momoWallet: 'Momo 钱包',
      paypal: 'PayPal',
      creditCard: '信用卡/借记卡',
      accountNumber: '帐号',
      accountHolder: '账户持有人',
      bankName: '银行',
      transferContent: '转账内容（订单号）',
      scanQR: '扫描二维码付款',
      paymentConfirmation: '我已完成付款',
      copy: '复制',
      copied: '已复制！',
      momoPhoneNumber: 'Momo 电话号码',
      paypalEmail: 'PayPal 邮箱',
    },
    affiliateDashboard: {
        title: '联盟仪表板',
        yourLink: '您的联盟链接',
        copy: '复制',
        copied: '已复制！',
        performance: '表现一览',
        clicks: '点击次数',
        sales: '销售额',
        commission: '佣金',
        recentSales: '最近销售',
        date: '日期',
        product: '产品',
        payoutSummary: '付款摘要',
        balance: '当前余额',
        requestPayout: '请求付款',
        close: '关闭',
    },
    aboutModal: {
        title: '关于 DMP AI Studio',
        content: `DMP AI Studio 是一个全面的 AI 解决方案平台，旨在为企业和个人赋能。我们将多代理 AI、自动支付和联盟收入共享系统集成到一个具有高端用户体验/用户界面的现代响应式设计中。我们的使命是让先进的 AI 易于访问和使用，并提供越南语、英语和中文的多语言支持，以服务全球受众。
        <br /><br />
        <b>联系信息：</b><br />
        人工智能开发团队：DMP AI Dev<br />
        地址：越南顺化市Vĩ Dạ区Nguyễn Bính街06号<br />
        电话：+84 0766771509 (越南)<br />
        Whatsapp: +84 0766771509<br />
        邮箱：dmpdevai@gmail.com / minhphu1509@gmail.com`,
        close: '关闭',
    },
    imageGeneratorModal: {
        title: 'AI 图像生成器',
        promptPlaceholder: '例如：一张猫宇航员骑着火箭穿越银河系的照片',
        generate: '生成图像',
        generating: '正在生成...',
        error: '生成图像失败。请再试一次。',
        close: '关闭',
        saveImage: '保存图像',
        saveImageFilenamePrompt: '为您的图像输入文件名（例如：我的猫.png）：',
        agentTitle: 'AI 艺术助手',
        welcomeMessage: '你好！我可以帮你打造完美的提示。你想创造什么？',
        chatPlaceholder: '询问提示想法...',
    },
  },
};