

// FIX: Import GoogleGenAI from @google/genai
import { GoogleGenAI } from "@google/genai";
import { AppInfo } from '../types';

const getSystemInstruction = (app?: AppInfo): string => {
  if (app) {
    return `You are a specialized AI sales agent for the app: '${app.name}'.
- App Description: ${app.description}.
- Price: ${app.price}.
- Your primary goal is to provide information about this specific app and persuade the user to purchase it.
- Be friendly, knowledgeable, and focus on the benefits of this app.
- Guide the user towards clicking the 'Proceed to Payment' button.
- If the user asks about other apps, briefly acknowledge their question but gently steer the conversation back to the app you are currently selling.
- Do not make up information. If you don't know an answer, say so.`;
  }

  return `You are a friendly and expert AI Business Agent for 'DMP AI Studio'. Your primary role is to act as a helpful sales and customer support assistant.
- Your tone should be professional, encouraging, and clear.
- Introduce the platform and its key benefits when asked.
- Analyze user needs to suggest the most suitable AI apps from the available list. When recommending apps, present them as a formatted list (using markdown) with a brief explanation for each suggestion.
- Guide users on pricing, payment processes, and account creation.
- Provide excellent post-purchase customer care and answer any questions about using the apps.
- If you don't know an answer, politely say that you will connect them with a human agent. Do not make up information.`;
};


export const sendMessageToAgent = async (message: string, app?: AppInfo): Promise<string> => {
  console.log("Sending message to AI Agent:", message, "with context:", app?.name);

  try {
    // Initialize the GoogleGenAI client inside the function to prevent module-level errors.
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-pro',
      contents: message,
      config: {
        systemInstruction: getSystemInstruction(app),
      }
    });
    return response.text;
  } catch (error) {
    console.error("Error calling Gemini API:", error);
    return "I'm sorry, I'm having trouble connecting right now. Please try again later.";
  }
};

export const generateImage = async (prompt: string): Promise<string> => {
  try {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    const response = await ai.models.generateImages({
      model: 'imagen-4.0-generate-001',
      prompt: prompt,
      config: {
        numberOfImages: 1,
        outputMimeType: 'image/png',
        aspectRatio: '1:1',
      },
    });

    if (response.generatedImages && response.generatedImages.length > 0) {
        const base64ImageBytes = response.generatedImages[0].image.imageBytes;
        return `data:image/png;base64,${base64ImageBytes}`;
    } else {
        throw new Error("No image was generated by the API.");
    }
  } catch (error) {
    console.error("Error calling Imagen API:", error);
    throw new Error("Failed to generate image. Please try again.");
  }
};